services:
  postgres:
    image: "postgres"
    logging:
      driver: local
    ports:
      - 9446:5432
    volumes:
      - postgres-volume:/var/postgresql_data
    environment:
      - PGDATA=/var/postgresql_data
      - POSTGRES_USER=backbase
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 3s
      timeout: 20s
      retries: 10
volumes:
  postgres-volume:

